name: elearner
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  lottie: ^3.0.0
  internet_connection_checker: ^1.0.0+1
  shimmer: ^3.0.0
  responsive_sizer: ^3.3.1
  firebase_database: ^11.0.2
  firebase_core: ^3.4.0
  flexivideoplayer: ^0.1.1
  video_player: ^2.9.1
  shared_preferences: ^2.2.3
  toastification: ^2.1.0
  flick_video_player: ^0.7.0
  visibility_detector: ^0.4.0+2
  otp_input_editor: ^0.0.9
  rflutter_alert: ^2.0.7
  cached_network_image: ^3.4.1
  responsive_grid_list: ^1.4.0
  image_stack: ^2.1.1
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  url_launcher: ^6.3.0
  intl: ^0.19.0
  image_picker: ^1.0.8
  image_cropper: ^5.0.1
  custom_date_range_picker: ^1.1.0
  google_maps_flutter: ^2.9.0
  map_location_picker: ^1.3.0
  flutter_keyboard_visibility: ^5.4.1
  location_geocoder: ^1.0.5
  dropdown_button2: ^2.3.9
#  googleapis: ^13.1.0
#  googleapis_auth: ^1.5.1
#  firebase_messaging: ^15.1.2




  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
   - assets/animationfile/
   - assets/images/

  fonts:
    - family: Nunito-Bold
      fonts:
        - asset: fonts/Nunito-Bold.ttf